name: Deploy School Website

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read subscription info
        id: subscription
        run: |
          SCHOOL_NAME="Class-activities-1565"   # ← معرف المدرسة
          
          START=$(jq -r .${SCHOOL_NAME}.start subscriptions.json)
          END=$(jq -r .${SCHOOL_NAME}.end subscriptions.json)
          TODAY=$(date +%Y-%m-%d)

          echo "اشتراك $SCHOOL_NAME يبدأ $START وينتهي $END (اليوم $TODAY)"

          if [[ "$TODAY" < "$START" || "$TODAY" > "$END" ]]; then
            echo "expired=true" >> $GITHUB_OUTPUT
          else
            echo "expired=false" >> $GITHUB_OUTPUT
          fi

      - name: Prepare expired page
        if: steps.subscription.outputs.expired == 'true'
        run: |
          mkdir out
          echo "<!DOCTYPE html><html><head><meta charset='utf-8'><title>انتهى الاشتراك</title></head><body><h1 style='text-align:center;color:red'>⚠️ تم إيقاف الخدمة لعدم تجديد الاشتراك</h1></body></html>" > out/index.html

      - name: Copy real website
        if: steps.subscription.outputs.expired == 'false'
        run: |
          mkdir out
          cp -r schools/Class-activities-1565/* out/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
